# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpWomenEngineerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StigmasFromReddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(default='python', max_length=100)),
                ('style', models.CharField(default='friendly', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='helpWomenEngineerApp',
        ),
    ]
